[FEAT] Add a SeqAn Version Badge to every inhouse app.
seqan/www.seqan.de pull request #69
Opened 2021-06-08 09:02 UTC by simonsasse

Resolves partly: https://github.com/seqan/www.seqan.de/issues/67

2021-06-08 09:31 UTC, eseiler commented
I think the badge could be a bit smaller (the box itself, font size seems good). I would also give seqan3 another color (green?).

Can you please rebase on master and also mark raptor?

2021-06-08 09:31 UTC, eseiler requested changes
see above

2021-06-08 09:58 UTC, eseiler approved these changes

2021-06-08 10:39 UTC, marehr commented on assets/css/style.scss
> +  background-color: $seqan-color;
```suggestion
  background-color: rgb(253, 253, 150); // pastel yellow
  border: 1px solid color.scale(rgb(251, 251, 70), $lightness: -20%); // 20% darker color
```

2021-06-08 10:40 UTC, marehr commented on assets/css/style.scss
> +  background-color: greenyellow;
```suggestion
  background-color: #77dd77;  // pastel green
  border: 1px solid color.scale(#77dd77, $lightness: -20%); // 20% darker color
```

2021-06-08 10:50 UTC, marehr commented on assets/css/style.scss
> +  border: 1px solid color.scale(#77dd77, $lightness: -20%); // 20% darker color
```suggestion
  border: 1px solid darken(#77dd77, 20%); // 20% darker color
```

2021-06-08 10:59 UTC, marehr commented on assets/css/style.scss
> +  background-color: rgb(#FDFD96); // pastel yellow
```suggestion
  background-color: #FDFD96; // pastel yellow
```

2021-06-08 11:20 UTC, marehr commented on assets/css/style.scss
> +  border: 1px solid darken(#77dd77, 20%); // 20% darker color
```suggestion
  background-color: #C1E1C1;  // pastel green
  border: 1px solid darken(#C1E1C1, 20%); // 20% darker color
```

2021-06-08 11:34 UTC, marehr commented
@eseiler , @simonsasse 

We have now three versions:

* https://www-seqan-de-87j4jjqej-seqan.vercel.app/apps/ (original) 
* https://www-seqan-de-7u92dud6m-seqan.vercel.app/apps/ (pastel yellow & green)
* https://www-seqan-de-95utwrzu1-seqan.vercel.app/apps/ (same pastel yellow but a more pastel green)

Which version do you prefer?

2021-06-08 11:39 UTC, eseiler commented
I think

> * https://www-seqan-de-95utwrzu1-seqan.vercel.app/apps/ (same pastel yellow but a more pastel green)

2021-06-08 12:21 UTC, simonsasse commented
I Personally like this one https://www-seqan-de-7u92dud6m-seqan.vercel.app/apps/ because of the more obvious green.
but I thats not a strong opinion :)

2021-06-11 07:12 UTC, simonsasse commented
> I think
> 
> > * https://www-seqan-de-95utwrzu1-seqan.vercel.app/apps/ (same pastel yellow but a more pastel green)

Lets go with this :)

2021-06-15 06:43 UTC, eseiler commented
I forgot if we decided something today, but I'd say you decide :)
Can you please rebase (again) and add the seqan3 badge to igenvar?

2021-06-15 07:47 UTC, eseiler commented
Let's do it like this, we can always change it later :)

2021-06-15 07:47 UTC, merged